version: "3"

services:
  gitea:
    image: gitea/gitea:1.16.8
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DOMAIN=${SERVER_ADDRESS}
      - ROOT_URL=http://${SERVER_ADDRESS}:3000
      #- HTTP_ADDR=${SERVER_ADDRESS}
      - LOCAL_ROOT_URL=http://${SERVER_ADDRESS}:3000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${SERVER_ADDRESS}:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${USER_NAME}
      - GITEA__database__PASSWD=${USER_PASSWORD}
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  drone:
    container_name: drone
    image: drone/drone:2.12
    restart: always
    depends_on:
      - gitea
      - db
    environment:
      # https://docs.drone.io/server/provider/gitea/
      - DRONE_SERVER_PORT=:3001
      - DRONE_DATABASE_DRIVER=postgres
      - DRONE_DATABASE_DATASOURCE=postgres://${USER_NAME}:${USER_PASSWORD}@${SERVER_ADDRESS}:5432/postgres?sslmode=disable
      - DRONE_GITEA_SERVER=http://${SERVER_ADDRESS}:3000/
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_HOST=${SERVER_ADDRESS}:3001
      - DRONE_TLS_AUTOCERT=false
      - DRONE_USER_CREATE=${USER_NAME}:${USER_PASSWORD},machine:false,admin:true,token:${DRONE_RPC_SECRET}
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
    ports:
      - "3001:3001"
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone:/data

  db:
    container_name: db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=${USER_PASSWORD}
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_DB=gitea
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
