version: "3"

services:
  dronerunner:
    image: drone/drone-runner-docker:1.8.2
    container_name: dronerunner
    restart: always
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=${DRONE_SERVER_ADDRESS}:3001
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${DRONE_RUNNER_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./artifacts:/var/artifacts
    ports:
      - "3000:3000"
